### ISSUE TITLE
sbt runMain fails with `no jep in java.library.path`

### ISSUE THREAD

**Issue by dportabella** [sushant-hiray/scala-python-example#1]
`sbt runMain` fails with `no jep in java.library.path`

```
$ docker run -ti hseeberger/scala-sbt
$ git clone https://github.com/sushant-hiray/scala-python-example.git
$ cd scala-python-example/
$ sbt "runMain com.sushant.example.JepAddExample"
[info] Set current project to scala-python-example (in build file:/root/scala-python-example/)
[info] Updating {file:/root/scala-python-example/}scala-python-example...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 2 Scala sources to /root/scala-python-example/target/scala-2.10/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.10.6. Compiling...
[info]   Compilation completed in 5.388 s
[info] Running com.sushant.example.JepAddExample
[error] (run-main-0) java.lang.UnsatisfiedLinkError: no jep in java.library.path
java.lang.UnsatisfiedLinkError: no jep in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at jep.Jep$TopInterpreter$1.run(Jep.java:118)
	at java.lang.Thread.run(Thread.java:745)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
[error] (compile:runMain) Nonzero exit code: 1
[error] Total time: 13 s, completed Apr 13, 2017 9:47:21 AM
```

I've tried also without docker, on my OSX, and I get the same problem.

**Comment by dportabella** [comment]
Solved by deleting the `lib` directory, and importing it from the `pip install jep` one.
Also, a fix on finding the python script file, and casting to Long instead of Int.

```
docker run -ti hseeberger/scala-sbt
apt-get update
apt-get install -y python3-pip
pip3 install jep

git clone https://github.com/sushant-hiray/scala-python-example.git
cd scala-python-example
sbt "runMain com.sushant.example.JepAddExample"
# java.lang.UnsatisfiedLinkError: no jep in java.library.path

rm -Rf ./lib
cp -r /usr/local/lib/python3.4/dist-packages/jep lib
sbt "runMain com.sushant.example.JepAddExample"
# jep.JepException: Invalid file: /root/scala-python-example/add.py

cp src/main/python/add.py .
sbt "runMain com.sushant.example.JepAddExample"
# [error] (run-main-0) java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer

perl -pi -e "s/Int/Long/g" src/main/scala/com/sushant/example/JepAddExample.scala
sbt "runMain com.sushant.example.JepAddExample"
5
5
# it works!
```

**Comment by sushant-hiray** [comment]
Thanks for the catch @dportabella 
I will push a fix more the casting issue.
This was a more of a toy example. I had also written a blog post a while ago with a much better example. You can have a look: https://sushant-hiray.me/posts/python-in-scala-stack/

**Comment by dportabella** [comment]
https://github.com/sushant-hiray/scala-python-example/pull/2
